# Task 3: Cuisine Classification

## Introduction

In this task, we aim to develop a machine learning model that classifies restaurants based on their cuisines. The classification of cuisines is essential for helping customers find restaurants that match their dietary preferences and culinary interests. By leveraging machine learning techniques, we can analyze restaurant data, identify patterns, and accurately classify cuisines.

The process will involve several key steps, including:

1. **Data Preprocessing:** We will handle missing values and encode categorical variables to ensure the dataset is ready for analysis.
2. **Data Splitting:** The dataset will be divided into training and testing sets to evaluate the model's performance effectively.
3. **Model Selection:** We will choose an appropriate classification algorithm, such as logistic regression or random forest, to train on the training data.
4. **Model Evaluation:** The performance of the model will be assessed using classification metrics like accuracy, precision, and recall on the testing data.
5. **Performance Analysis:** Finally, we will analyze the model's performance across different cuisines and identify any challenges or biases that may arise during classification.

Through this task, we aim to build a robust classification model that can assist users in discovering restaurants based on their preferred cuisines.


### Step 1: Load the Dataset

We begin by loading the restaurant dataset, which contains various features related to the restaurants, including their cuisines.

```python
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
df = pd.read_csv("/content/Dataset.csv")

# Display the first few rows of the dataframe
df.head()

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv("/content/Dataset.csv")
df.head()

Restaurant ID         Restaurant Name  Country Code              City  \
0        6317637        Le Petit Souffle           162       Makati City   
1        6304287        Izakaya Kikufuji           162       Makati City   
2        6300002  Heat - Edsa Shangri-La           162  Mandaluyong City   
3        6318506                    Ooma           162  Mandaluyong City   
4        6314302             Sambo Kojin           162  Mandaluyong City   

                                             Address  \
0  Third Floor, Century City Mall, Kalayaan Avenu...   
1  Little Tokyo, 2277 Chino Roces Avenue, Legaspi...   
2  Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...   
3  Third Floor, Mega Fashion Hall, SM Megamall, O...   
4  Third Floor, Mega Atrium, SM Megamall, Ortigas...   

                                     Locality  \
0   Century City Mall, Poblacion, Makati City   
1  Little Tokyo, Legaspi Village, Makati City   
2  Edsa Shangri-La, Ortigas, Mandaluyong City   
3      SM Megamall, Ortigas, Mandaluyong City   
4      SM Megamall, Ortigas, Mandaluyong City   

                                    Locality Verbose   Longitude   Latitude  \
0  Century City Mall, Poblacion, Makati City, Mak...  121.027535  14.565443   
1  Little Tokyo, Legaspi Village, Makati City, Ma...  121.014101  14.553708   
2  Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...  121.056831  14.581404   
3  SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.056475  14.585318   
4  SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.057508  14.584450   

                           Cuisines  ...          Currency Has Table booking  \
0        French, Japanese, Desserts  ...  Botswana Pula(P)               Yes   
1                          Japanese  ...  Botswana Pula(P)               Yes   
2  Seafood, Asian, Filipino, Indian  ...  Botswana Pula(P)               Yes   
3                   Japanese, Sushi  ...  Botswana Pula(P)                No   
4                  Japanese, Korean  ...  Botswana Pula(P)               Yes   

  Has Online delivery Is delivering now Switch to order menu Price range  \
0                  No                No                   No           3   
1                  No                No                   No           3   
2                  No                No                   No           4   
3                  No                No                   No           4   
4                  No                No                   No           4   

   Aggregate rating  Rating color Rating text Votes  
0               4.8    Dark Green   Excellent   314  
1               4.5    Dark Green   Excellent   591  
2               4.4         Green   Very Good   270  
3               4.9    Dark Green   Excellent   365  
4               4.8    Dark Green   Excellent   229  

[5 rows x 21 columns]

In [ ]:
# Print the columns of the DataFrame
print(df.columns)

Index(['Restaurant ID', 'Restaurant Name', 'Country Code', 'City', 'Address',
       'Locality', 'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Switch to order menu',
       'Price range', 'Aggregate rating', 'Rating color', 'Rating text',
       'Votes'],
      dtype='object')


In [ ]:
df.dtypes

Restaurant ID             int64
Restaurant Name          object
Country Code              int64
City                     object
Address                  object
Locality                 object
Locality Verbose         object
Longitude               float64
Latitude                float64
Cuisines                 object
Average Cost for two      int64
Currency                 object
Has Table booking        object
Has Online delivery      object
Is delivering now        object
Switch to order menu     object
Price range               int64
Aggregate rating        float64
Rating color             object
Rating text              object
Votes                     int64
dtype: object

### Step 2: Data Preprocessing

In this step, we will preprocess the dataset by checking for missing values and handling them appropriately. We will begin by identifying the total number of null values in each column. This information will help us understand the extent of missing data within the dataset.

Based on our findings, we will then decide to drop any rows that contain null values. This process is essential as having missing data can negatively impact the performance of our machine learning model. By ensuring that our dataset is clean and complete, we set a solid foundation for the subsequent steps in our classification task.


In [ ]:
# Check for total null values in each column
null_values = df.isnull().sum()

# Display the total null values for each column
print(null_values)


Restaurant ID           0
Restaurant Name         0
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                9
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0
dtype: int64


In [ ]:
# Drop columns with null values
df = df.dropna(axis=0, how='any')

# Display the remaining columns
print(df.columns)


Index(['Restaurant ID', 'Restaurant Name', 'Country Code', 'City', 'Address',
       'Locality', 'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Switch to order menu',
       'Price range', 'Aggregate rating', 'Rating color', 'Rating text',
       'Votes'],
      dtype='object')


### Step 3: Feature Selection

In this step, we will refine our dataset by dropping unnecessary columns that do not contribute to the classification task. We have identified a list of columns that we consider redundant or irrelevant for our analysis. These columns include details such as the restaurant ID, name, address, and geographical coordinates, which do not provide meaningful information for predicting the cuisine type.

By removing these columns, we can simplify our dataset and focus on the features that are more relevant to our classification task. After dropping the unnecessary columns, we will display the updated dataframe to confirm the changes.


In [ ]:
import pandas as pd

# List of columns to drop
columns_to_drop = [
    'Restaurant ID',
    'Restaurant Name',
    'Address',
    'Locality',
    'Locality Verbose',
    'Longitude',
    'Latitude',
    'Currency',
    'Rating color',
    'Rating text',
    'Votes',
    'Aggregate rating'
]

# Drop the unnecessary columns
df = df.drop(columns=columns_to_drop)

# Check the dataframe after dropping columns
df.head()

Country Code              City                          Cuisines  \
0           162       Makati City        French, Japanese, Desserts   
1           162       Makati City                          Japanese   
2           162  Mandaluyong City  Seafood, Asian, Filipino, Indian   
3           162  Mandaluyong City                   Japanese, Sushi   
4           162  Mandaluyong City                  Japanese, Korean   

   Average Cost for two Has Table booking Has Online delivery  \
0                  1100               Yes                  No   
1                  1200               Yes                  No   
2                  4000               Yes                  No   
3                  1500                No                  No   
4                  1500               Yes                  No   

  Is delivering now Switch to order menu  Price range  
0                No                   No            3  
1                No                   No            3  
2                No                   No            4  
3                No                   No            4  
4                No                   No            4

In [ ]:
df.dtypes

Country Code             int64
City                    object
Cuisines                object
Average Cost for two     int64
Has Table booking       object
Has Online delivery     object
Is delivering now       object
Switch to order menu    object
Price range              int64
dtype: object

In [ ]:
df.isnull().sum()

Country Code            0
City                    0
Cuisines                0
Average Cost for two    0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
dtype: int64

### Step 4: Encoding Categorical Variables

In this step, we will encode categorical variables in our dataset to prepare it for the machine learning model. Since many machine learning algorithms require numerical input, we will use the Label Encoding technique to convert categorical variables into a numerical format.

We have identified several binary categorical variables, including 'City', 'Cuisines', 'Has Table booking', 'Has Online delivery', 'Is delivering now', and 'Switch to order menu'. Using the `LabelEncoder`, we will transform these columns so that each unique category is represented by a numerical value.

After applying label encoding, we will display the first few rows of the updated dataframe to verify the changes.


In [ ]:
from sklearn.preprocessing import LabelEncoder

# Initialize LabelEncoder
le = LabelEncoder()

# Apply Label Encoding to the 'Cuisines' column
# Encode binary categorical variables
binary_columns = ['City','Cuisines','Has Table booking', 'Has Online delivery', 'Is delivering now', 'Switch to order menu']

for column in binary_columns:
    df[column] = le.fit_transform(df[column])

# Check the first few rows to see the changes
df.head()


Country Code  City  Cuisines  Average Cost for two  Has Table booking  \
0           162    73       920                  1100                  1   
1           162    73      1111                  1200                  1   
2           162    75      1671                  4000                  1   
3           162    75      1126                  1500                  0   
4           162    75      1122                  1500                  1   

   Has Online delivery  Is delivering now  Switch to order menu  Price range  
0                    0                  0                     0            3  
1                    0                  0                     0            3  
2                    0                  0                     0            4  
3                    0                  0                     0            4  
4                    0                  0                     0            4

### Step 5: Outlier Removal from the Cuisines Column

In this step, we will address the presence of outlier cuisines in our dataset. Outliers in this context refer to cuisines that appear infrequently and may not provide meaningful insights for our classification task.

To handle this, we will take the following approach:

1. **Count Occurrences**: We will first count the occurrences of each cuisine type in the dataset. This will help us understand the distribution of cuisines and identify any that are rare.

2. **Define Threshold**: A threshold will be set to determine what constitutes a "rare" cuisine. In our case, we have chosen a threshold of 3, meaning any cuisine that appears less than 3 times in the dataset will be considered rare.

3. **Identify and Replace Rare Cuisines**: We will identify cuisines that fall below the threshold and replace them with a generic label, "Other". This allows us to reduce the dimensionality of our classification problem by consolidating infrequently occurring cuisines.

4. **Assign Numeric Value**: To further simplify the encoding, we will replace the label "Other" with a numeric value, for instance, -1. This will help maintain a numeric format across the 'Cuisines' column.

5. **Common Cuisines Handling**: Similarly, we will define a threshold for common cuisines. Any cuisine that occurs more frequently than this threshold (set to 50) will be labeled as "Common". We will replace this label with another numeric value, such as -2.

After performing these operations, we will check the updated class distribution to ensure the changes have been made successfully. This will help us maintain a cleaner dataset with relevant classes for our machine learning model.


In [ ]:
# Check the distribution of the target variable 'Cuisines'
class_distribution = df['Cuisines'].value_counts()
print(class_distribution)

# Optionally, display the distribution as a percentage
class_distribution_percentage = df['Cuisines'].value_counts(normalize=True) * 100
class_distribution_percentage


Cuisines
1306    936
1329    511
497     354
828     354
1514    334
       ... 
225       1
1548      1
599       1
200       1
1110      1
Name: count, Length: 1825, dtype: int64


Cuisines
1306    9.809264
1329    5.355271
497     3.709914
828     3.709914
1514    3.500314
          ...   
225     0.010480
1548    0.010480
599     0.010480
200     0.010480
1110    0.010480
Name: proportion, Length: 1825, dtype: float64

In [ ]:
df.dtypes


Country Code            int64
City                    int64
Cuisines                int64
Average Cost for two    int64
Has Table booking       int64
Has Online delivery     int64
Is delivering now       int64
Switch to order menu    int64
Price range             int64
dtype: object

In [ ]:
print(len(df['Cuisines'].unique()))

1825


In [ ]:
import pandas as pd

# Assuming df is your DataFrame
# Replace 'Cuisines' with the actual column name if it's different
most_frequent_cuisine = df['Cuisines'].value_counts().idxmax()
most_frequent_count = df['Cuisines'].value_counts().max()

print(f"The most frequent cuisine is: {most_frequent_cuisine}")
print(f"Number of occurrences: {most_frequent_count}")


The most frequent cuisine is: 1306
Number of occurrences: 936


In [ ]:
import pandas as pd

# Assuming 'df' is your DataFrame containing the cuisines

# Count occurrences of each cuisine
cuisine_counts = df['Cuisines'].value_counts()

# Define a threshold for rare cuisines
threshold = 3  # Set the threshold for combining classes

# Identify rare cuisines (less than the threshold)
rare_cuisines = cuisine_counts[cuisine_counts < threshold].index

# Replace rare cuisines with 'Other'
df['Cuisines'] = df['Cuisines'].replace(rare_cuisines, 'Other')

# Replace 'Other' with -1
df['Cuisines'] = df['Cuisines'].replace('Other', 1826)

# Check the updated class distribution
print(df['Cuisines'].value_counts())


Cuisines
1826    1696
1306     936
1329     511
828      354
497      354
        ... 
1254       3
1202       3
1583       3
217        3
22         3
Name: count, Length: 339, dtype: int64


<ipython-input-264-b0cf46597814>:18: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Cuisines'] = df['Cuisines'].replace('Other', 1826)


In [ ]:
import pandas as pd

# Assuming 'df' is your DataFrame containing the cuisines

# Count occurrences of each cuisine
cuisine_counts = df['Cuisines'].value_counts()

# Define a threshold for common cuisines
common_threshold = 50  # Set the threshold for common classes

# Identify common cuisines (greater than the threshold)
common_cuisines = cuisine_counts[cuisine_counts >= common_threshold].index

# Replace common cuisines with 'Common'
df['Cuisines'] = df['Cuisines'].replace(common_cuisines, 'Common')

# Replace 'Common' with a numeric value, e.g., -2
df['Cuisines'] = df['Cuisines'].replace('Common', 1827)

# Check the updated class distribution
print(df['Cuisines'].value_counts())


Cuisines
1827    7076
895       49
1655      49
865       46
1559      46
        ... 
189        3
1583       3
1622       3
1688       3
1532       3
Name: count, Length: 305, dtype: int64


<ipython-input-265-17c56b25d4c3>:18: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Cuisines'] = df['Cuisines'].replace('Common', 1827)


### Step 6: Model Training and Evaluation

In this final step, we will train and evaluate several machine learning models to classify restaurants based on their cuisines. We will utilize various classification algorithms and compare their performance using appropriate metrics.

1. **Prepare Features and Target**: We first separate the features (X) from the target variable (y), which is the 'Cuisines' column in our DataFrame.

2. **Split the Dataset**: The dataset will be split into training and testing sets, with 20% of the data reserved for testing. We will also ensure that the split maintains the class distribution of cuisines using stratification.

3. **Model Selection and Training**: We will initialize and train the following classifiers on the training set:
   - **Random Forest Classifier**: A robust model known for its ability to handle high-dimensional data and prevent overfitting.
   - **Support Vector Classifier (SVC)**: A powerful classifier that aims to find the optimal hyperplane for classification tasks.
   - **K-Nearest Neighbors (KNN)**: A simple and effective algorithm that classifies based on the closest training samples in the feature space.
   - **Logistic Regression**: A linear model suitable for binary and multiclass classification problems.
   - **Gradient Boosting Classifier**: An ensemble method that builds models sequentially to correct errors made by previous models.

4. **Predictions and Evaluation**: After training each model, we will make predictions on the test set. The performance of each classifier will be evaluated using:
   - **Confusion Matrix**: This provides insight into the correct and incorrect predictions made by the model.
   - **Classification Report**: This includes metrics such as precision, recall, and F1-score for each class, allowing us to assess the effectiveness of the classifiers.

By comparing the performance of these models, we can identify which classifier is best suited for our restaurant cuisine classification task and analyze any challenges or biases encountered during the classification process.


In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Assuming 'filtered_df' is your DataFrame with combined cuisines

# Prepare features (X) and target (y)
X = df.drop('Cuisines', axis=1)  # Drop the target column to get features
y = df['Cuisines']  # Target variable (combined cuisines)

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Initialize and train the Random Forest classifier
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = rf_model.predict(X_test)

# Evaluate the model
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))


Confusion Matrix:
[[   0    0    0 ...    0    0    1]
 [   0    1    0 ...    0    0    5]
 [   0    0    0 ...    0    0    1]
 ...
 [   0    0    0 ...    0    0    3]
 [   0    0    0 ...    0    0    1]
 [   0    0    0 ...    0    0 1347]]

Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           6       1.00      0.17      0.29         6
          16       0.00      0.00      0.00         1
          18       0.00      0.00      0.00         1
          21       0.00      0.00      0.00         1
          22       0.00      0.00      0.00         1
          29       0.00      0.00      0.00         3
          35       0.00      0.00      0.00         1
          54       0.00      0.00      0.00         4
          55       0.00      0.00      0.00         1
          69       0.00      0.00      0.00         1
          83       0.00      0.00      0.00         0
          98       0.00    

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_

In [ ]:
from sklearn.svm import SVC

# Initialize and train Support Vector Classifier
svc = SVC()
svc.fit(X_train, y_train)

# Predictions
y_pred_svc = svc.predict(X_test)

# Evaluation
print("Results for Support Vector Classifier:")
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_svc))
print("\nClassification Report:")
print(classification_report(y_test, y_pred_svc, zero_division=0))
print("-" * 60)


Results for Support Vector Classifier:
Confusion Matrix:
[[   0    0    0 ...    0    0    3]
 [   0    0    0 ...    0    0    3]
 [   0    0    0 ...    0    0    1]
 ...
 [   0    0    0 ...    0    0    1]
 [   0    0    0 ...    0    0    1]
 [   0    0    0 ...    0    0 1428]]

Classification Report:
              precision    recall  f1-score   support

           6       0.00      0.00      0.00         3
          16       0.00      0.00      0.00         3
          18       0.00      0.00      0.00         1
          21       0.00      0.00      0.00         1
          29       0.00      0.00      0.00         2
          35       0.00      0.00      0.00         2
          54       0.00      0.00      0.00         4
          55       0.00      0.00      0.00         2
          78       0.00      0.00      0.00         2
          83       0.00      0.00      0.00         1
          98       0.00      0.00      0.00         1
         102       0.00      0.00      0.0

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

# Initialize and train K-Nearest Neighbors Classifier
knn_classifier = KNeighborsClassifier()
knn_classifier.fit(X_train, y_train)

# Predictions
y_pred_knn = knn_classifier.predict(X_test)

# Evaluation
print("Results for K-Nearest Neighbors Classifier:")
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_knn))
print("\nClassification Report:")
print(classification_report(y_test, y_pred_knn, zero_division=0))
print("-" * 60)


Results for K-Nearest Neighbors Classifier:
Confusion Matrix:
[[   0    0    0 ...    0    0    3]
 [   0    0    0 ...    0    0    3]
 [   0    1    0 ...    0    0    0]
 ...
 [   0    0    0 ...    0    0    1]
 [   0    0    0 ...    0    0    1]
 [   2    2    0 ...    0    0 1367]]

Classification Report:
              precision    recall  f1-score   support

           6       0.00      0.00      0.00         3
          16       0.00      0.00      0.00         3
          18       0.00      0.00      0.00         1
          21       0.00      0.00      0.00         1
          22       0.00      0.00      0.00         0
          29       0.00      0.00      0.00         2
          35       0.00      0.00      0.00         2
          54       0.00      0.00      0.00         4
          55       0.00      0.00      0.00         2
          78       0.00      0.00      0.00         2
          83       0.00      0.00      0.00         1
          90       0.00      0.00    

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

# Initialize and train Logistic Regression model
log_reg = LogisticRegression(solver='liblinear', max_iter=1000)  # or 'saga'
log_reg.fit(X_train, y_train)

# Predictions
y_pred_log_reg = log_reg.predict(X_test)

# Evaluation
print("Results for Logistic Regression:")
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_log_reg))
print("\nClassification Report:")
print(classification_report(y_test, y_pred_log_reg, zero_division=0))
print("-" * 60)


Results for Logistic Regression:
Confusion Matrix:
[[   0    0    0 ...    0    0    3]
 [   0    0    0 ...    0    0    3]
 [   0    0    0 ...    0    0    1]
 ...
 [   0    0    0 ...    0    0    1]
 [   0    0    0 ...    0    0    1]
 [   0    0    0 ...    0    0 1428]]

Classification Report:
              precision    recall  f1-score   support

           6       0.00      0.00      0.00         3
          16       0.00      0.00      0.00         3
          18       0.00      0.00      0.00         1
          21       0.00      0.00      0.00         1
          29       0.00      0.00      0.00         2
          35       0.00      0.00      0.00         2
          54       0.00      0.00      0.00         4
          55       0.00      0.00      0.00         2
          78       0.00      0.00      0.00         2
          83       0.00      0.00      0.00         1
          98       0.00      0.00      0.00         1
         102       0.00      0.00      0.00     

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

# Initialize and train Gradient Boosting Classifier
gb_classifier = GradientBoostingClassifier()
gb_classifier.fit(X_train, y_train)

# Predictions
y_pred_gb = gb_classifier.predict(X_test)

# Evaluation
print("Results for Gradient Boosting Classifier:")
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_gb))
print("\nClassification Report:")
print(classification_report(y_test, y_pred_gb, zero_division=0))
print("-" * 60)


Results for Gradient Boosting Classifier:
Confusion Matrix:
[[  0   0   0 ...   0   0   1]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0   0 ...   0   0   1]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0 876]]

Classification Report:
              precision    recall  f1-score   support

           6       0.00      0.00      0.00         3
          16       0.00      0.00      0.00         3
          18       0.00      0.00      0.00         1
          21       0.00      0.00      0.00         1
          29       0.00      0.00      0.00         2
          35       0.00      0.00      0.00         2
          54       0.00      0.00      0.00         4
          55       0.00      0.00      0.00         2
          69       0.00      0.00      0.00         0
          78       0.00      0.00      0.00         2
          83       0.00      0.00      0.00         1
          98       0.00      0.00      0.00         1
         102       0.

### Conclusion

In this task of classifying restaurants based on their cuisines, we evaluated multiple machine learning classifiers. The **Support Vector Classifier (SVC)** and **Logistic Regression** both yielded the best performance, achieving an accuracy of **75%** on the test set.

**Logistic Regression Results:**
- Accuracy: 0.75
- Macro Average: 0.00 for precision, recall, and F1-score.
- Weighted Average:
  - Precision: 0.56
  - Recall: 0.75
  - F1-Score: 0.64

**Support Vector Classifier Results:**
- Accuracy: 0.75
- Macro Average: 0.00 for precision, recall, and F1-score.
- Weighted Average:
  - Precision: 0.56
  - Recall: 0.75
  - F1-Score: 0.64

These results indicate that while both models performed similarly in terms of accuracy, there are significant challenges in precision and recall, as suggested by the macro averages being zero. This points to potential biases or class imbalances in the dataset, which may require further investigation and preprocessing to enhance model performance.

Overall, the findings demonstrate that SVC and Logistic Regression are promising models for restaurant cuisine classification, but improvements in class balance and feature selection may lead to better classification outcomes in future iterations.
